[versions]
android-compile = "36"
android-min = "21"
atomicfu = "0.31.0"
datadog-multiplatform = "1.5.0"
datadog-npm = "6.28.0" # https://www.npmjs.com/package/@datadog/browser-logs
jvm-toolchain = "11"
ktor = "3.4.0"
serialization = "1.10.0"

[libraries]
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
datadog-multiplatform-logs = { module = "com.datadoghq:dd-sdk-kotlin-multiplatform-logs", version.ref = "datadog-multiplatform" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.4.0" }
ktor-client-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
nserrorkt = { module = "com.rickclephas.kmp:nserror-kt", version = "0.2.0" }
result = { module = "com.michael-bull.kotlin-result:kotlin-result", version = "2.1.0" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-library = { id = "com.android.library", version = "9.0.1" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.3.10" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.3.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
